name: secmail_crypto_flutter
description: Flutter/OpenPGP addon for secmail_crypto_sdk (openpgp plugin + secure storage).
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage:
    git:
      url: https://github.com/fl-start/flutter_secure_storage.git
      ref: develop
      path: flutter_secure_storage
  openpgp: ^3.10.7
  secmail_crypto_sdk:
    path: ../..

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
